services:
  keycloak:
    image: keycloak/keycloak:26.3
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./src/test/resources/keycloak/myrealm-realm.json:/opt/keycloak/data/import/realm.json
    command:
      - "start-dev"
